const trades = [
	{
		id: "1",
		date: "01/12/2021",
		accountBalance: "200.00",
		currencyPair: "AUD/USD",
		Type: "Long",
		profit: "2.88",
		return: "1.44",
		comment: "First trade of the month.",
	},
	{
		id: "2",
		date: "02/12/2021",
		accountBalance: "202.88",
		currencyPair: "GBP/USD",
		Type: "Long",
		profit: "-1.88",
		return: "-0.92",
		comment: "Second trade of the month.",
	},
	{
		id: "3",
		date: "02/12/2021",
		accountBalance: "202.88",
		currencyPair: "EUR/USD",
		Type: "Long",
		profit: "-3.2",
		return: "-1.57",
		comment: "Third trade of the month.",
	},
	{
		id: "4",
		date: "03/12/2021",
		accountBalance: "197.8",
		currencyPair: "AUD/USD",
		Type: "Long",
		profit: "5.33",
		return: "2.69",
		comment: "Forth trade of the month.",
	},
	{
		id: "5",
		date: "04/12/2021",
		accountBalance: "203.13",
		currencyPair: "USD/CAD",
		Type: "Long",
		profit: "-0.31",
		return: "-0.15",
		comment: "Fifth trade of the month.",
	},
];

export default trades;
